### ISSUE TITLE
Package fails to install on Ubuntu Trusty

### ISSUE THREAD

**Issue by centromere** [cablehead/python-consul#118] opened 2016-07-14 19:44 UTC
When I attempt to install this package in to a venv on Ubuntu Trusty, I get this error:

```
Searching for python-consul
Reading https://pypi.python.org/simple/python-consul/
Best match: python-consul 0.6.1
Downloading https://pypi.python.org/packages/3c/9e/3811c8e5b6de412a0697b4102cda0473bde09dfbca9692d20a3ad46675a5/python-consul-0.6.1.tar.gz#md5=02eb3bc92e24da0414ac54770ae7d5f1
Processing python-consul-0.6.1.tar.gz
Writing /tmp/easy_install-6ccnqs/python-consul-0.6.1/setup.cfg
Running python-consul-0.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6ccnqs/python-consul-0.6.1/egg-dist-tmp-WvlZKW
  File "build/bdist.linux-x86_64/egg/consul/aio.py", line 41
    resp = yield from aiohttp.request(method, uri,
                    ^
SyntaxError: invalid syntax
```

```
python --version
Python 2.7.6
```

**Comment by cablehead** [comment] 2016-12-18 21:23
This looks like the installer is running python 3 specific versions of python-consul. Could someone using Ubuntu Trusty investigate?

**Comment by cablehead** [comment] 2016-12-18 22:16
Might be related to #123

**Comment by abn** [comment] 2017-07-30 11:41
Tried with a ubuntu trusty container and cannot reproduce this with neither `0.6.1` or latest. Closing.
```sh
$ docker run --rm -it ubuntu:trusty sh
# apt-get update && apt-get install -y python python-pip 
Ign http://archive.ubuntu.com trusty InRelease       
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
[TRUNCATED]
# pip install python-consul
Downloading/unpacking python-consul
  Downloading python-consul-0.7.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-consul/setup.py) egg_info for package python-consul
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/lib/python2.7/dist-packages (from python-consul)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/dist-packages (from python-consul)
Installing collected packages: python-consul
  Running setup.py install for python-consul
    
Successfully installed python-consul
Cleaning up...
# pip uninstall python-consul
Uninstalling python-consul:
[TRUNCATED]
  Successfully uninstalled python-consul
# pip install python-consul==0.6.1
Downloading/unpacking python-consul==0.6.1
  Downloading python-consul-0.6.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-consul/setup.py) egg_info for package python-consul
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/lib/python2.7/dist-packages (from python-consul==0.6.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python2.7/dist-packages (from python-consul==0.6.1)
Installing collected packages: python-consul
  Running setup.py install for python-consul
    
Successfully installed python-consul
Cleaning up...
#
```
Attempted with python3 too.
```sh
# pip3 install python-consul
Downloading/unpacking python-consul
  Downloading python-consul-0.7.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-consul/setup.py) egg_info for package python-consul
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/lib/python3/dist-packages (from python-consul)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python3/dist-packages (from python-consul)
Installing collected packages: python-consul
  Running setup.py install for python-consul
    
Successfully installed python-consul
Cleaning up...
# pip3 uninstall python-consul
Uninstalling python-consul:
[TRUNCATED]
  Successfully uninstalled python-consul
# pip3 uninstall python-consul==0.6.1
Cannot uninstall requirement python-consul, not installed
Storing debug log for failure in /root/.pip/pip.log
# pip3 install python-consul==0.6.1
Downloading/unpacking python-consul==0.6.1
  Downloading python-consul-0.6.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/python-consul/setup.py) egg_info for package python-consul
    
Requirement already satisfied (use --upgrade to upgrade): requests>=2.0 in /usr/lib/python3/dist-packages (from python-consul==0.6.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in /usr/lib/python3/dist-packages (from python-consul==0.6.1)
Installing collected packages: python-consul
  Running setup.py install for python-consul
    
Successfully installed python-consul
Cleaning up...
# 
```

**Closed by abn** 2017-07-30 11:41 UTC
Labels: help wanted

**Comment by abn** [comment] 2017-07-30 11:44
Just as a note for anyone stumbling across here, the root cause of the reported issue *could* be some some setup weirdness caused by broken/unexpected environments.
